### PR TITLE
ufs.go: return only full directory entries.

### PR DESCRIPTION
**Pull request by aki5**
mount driver in harvey (plan9) does not deal with partial directory entries.
Hence, I changed ufs.go to not return them.
Performance isn't great, but at least it seems to work.

### CODE REVIEW

**Comment by mischief** [comment]
what happens when the dir exceeds iounit?

**Comment by rminnich** [comment]
I think it will be bad, but if they use that small an iounit, they deserve what they get IMHO :-)

**Comment by mischief** [comment]
And if the directory is simply very large...?

**Comment by aki5** [comment]
large directories are exactly the reason why this change needed to be made,
but the point about a directory entry being too large to fit is perfectly
valid.
the read returns you zero in that case.

**Pull request merged**
